# -*- coding: utf-8 -*-
"""aipi-510-week12-interactive-ml-pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sr28TNSRlYwNGFuv9s95Ou_Ax1z0_agc
"""

# Following two lines of code generated by ChatGPT 5.0 at 12:33 PM
import seaborn as sns
titanic_df = sns.load_dataset("titanic")

clean_df = titanic_df.dropna(subset=["age", "survived"]) # Generated by ChatGPT 5.0 at 12:42 PM


from sklearn.model_selection import train_test_split
X = clean_df[["age"]]
y = clean_df["survived"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression() # default parameters
model.fit(X_train, y_train)

y_preds = model.predict(X_test)

from sklearn.metrics import accuracy_score
test_accuracy = accuracy_score(y_test, y_preds)
print("Logistic Regression Model's Test Accuracy:", test_accuracy)